spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles:
    active: local
  config:
    use-legacy-processing: true
server:
  port: 8081