spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:travel;DB_CLOSE_DELAY=-1
    username: sa
    password:
    sql-script-encoding: utf-8
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml